# rm -rf ./node_modules/tms-koa-account/index.js
cp -rf ../admin ./node_modules/tms-koa-account
cp -rf ../context ./node_modules/tms-koa-account
cp -rf ../models ./node_modules/tms-koa-account
cp -rf ../app.js ./node_modules/tms-koa-account
cp -rf ../config.js ./node_modules/tms-koa-account
cp -rf ../index.js ./node_modules/tms-koa-account
cp -rf ../router.js ./node_modules/tms-koa-account
cp -rf ../package.json ./node_modules/tms-koa-account